spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 121.196.27.204:8848 # Nacos 服务器地址
        namespace: bdfe477e-b847-4f97-8ac0-a6a3b9f3da24 # Nacos 命名空间 dev 的编号